[package]
name = "cargo-docs-rs"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
