[package]
name = "cargo-docs-rs"
version = "0.1.5"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["development-tools::cargo-plugins"]
description = "Immitate the documentation build that docs.rs would do"
edition = "2021"
keywords = ["cargo", "subcommand", "docs-rs", "documentation"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/cargo-docs-rs"

[dependencies]
anyhow = "1"
cargo-subcommand-metadata = "0.1"
clap = { version = "4", features = ["derive", "deprecated"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.8"
